[package]
name = "bevy_flicker"
version = "0.1.0"
edition = "2021"
license = "Unlicense"
keywords = ["gamedev", "graphics", "bevy", "bevy_plugin"]
categories = ["game-development"]
authors = ["bilowik"]
description = "An easy to use event-based system to apply brief overlays to sprites and meshes"


[dependencies]
bevy = "0.10.1"


[features]
warnings = []

